config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  resources :blogs
  resources :calculates
  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end 
  end

  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :microposts, only: [:create, :destroy]
  resources :static_pages
  match '/home', to: 'static_pages#home', via: 'get'
  
  namespace :admin do
    resources :microposts, :users
    get '', to: 'dashboard#index', as: '/'
  end

  

end

app/models/calculate.rb
class Calculate < ActiveRecord::Base

def daily_sum
	@calculates = Calculate.all
		
end # end daily_sum

end

app/controllers/calculates_controller.rb
class CalculatesController < ApplicationController
  before_action :set_calculate, only: [:show, :edit, :update, :destroy]

  # GET /calculates
  # GET /calculates.json
  def index
    @calculates = Calculate.order('spent_on')
    @calculate_per_day = @calculates.group_by { |c| c.spent_on.beginning_of_day }

  end

  # GET /calculates/1
  # GET /calculates/1.json
  def show
  end

  # GET /calculates/new
  def new
    @calculate = Calculate.new
  end

  # GET /calculates/1/edit
  def edit
  end

  # POST /calculates
  # POST /calculates.json
  def create
    @calculate = Calculate.new(calculate_params)

    respond_to do |format|
      if @calculate.save
        format.html { redirect_to @calculate, notice: 'Calculate was successfully created.' }
        format.json { render :show, status: :created, location: @calculate }
      else
        format.html { render :new }
        format.json { render json: @calculate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /calculates/1
  # PATCH/PUT /calculates/1.json
  def update
    respond_to do |format|
      if @calculate.update(calculate_params)
        format.html { redirect_to @calculate, notice: 'Calculate was successfully updated.' }
        format.json { render :show, status: :ok, location: @calculate }
      else
        format.html { render :edit }
        format.json { render json: @calculate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /calculates/1
  # DELETE /calculates/1.json
  def destroy
    @calculate.destroy
    respond_to do |format|
      format.html { redirect_to calculates_url, notice: 'Calculate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_calculate
      @calculate = Calculate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def calculate_params
      params.require(:calculate).permit(:name, :money_spent, :spent_on, :daily_sum)
    end

end

app/helpers/calculates_helper.rb
module CalculatesHelper
end

app/views/calculates/_form.html.erb
<%= form_for(@calculate) do |f| %>
  <% if @calculate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@calculate.errors.count, "error") %> prohibited this calculate from being saved:</h2>

      <ul>
      <% @calculate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :spent_on %><br>
    <%= f.date_select :spent_on, :order => [:month, :day, :year] %>
  </div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :money_spent %><br>
    <%= f.number_field :money_spent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/calculates/edit.html.erb
<h1>Editing calculate</h1>

<%= render 'form' %>

<%= link_to 'Show', @calculate %> |
<%= link_to 'Back', calculates_path %>

app/views/calculates/index.html.erb
<h4><%= link_to 'Add New Item', new_calculate_path %></h4>

<h3>가계부</h3>
<% @calculate_per_day.sort.reverse.each do |day, calculate| %>
<% daily_sum = 0.0 %>
 
  <div>
    <h2><%= day.strftime('%B %d, %y') %></h2>
  </div>
 
 <% @calculate_per_day[day].each do |calculate| %>
  <div>
    <span style="padding-right:15px"><%= calculate.name %></span>
    <span style="padding-right:15px"><%= number_to_currency(calculate.money_spent) %></span>
    <span style="padding-left:50px;">
    <%= link_to 'Edit', edit_calculate_path(calculate) %>
    <%= link_to 'Destroy', calculate, method: :delete, data: { confirm: 'Are you sure?' } %>
    </span>
  </div>
  <% daily_sum = daily_sum + calculate.money_spent %>
    <% end %>
  
  <div style="padding-top:15px">
    Sum: <strong><%= number_to_currency(daily_sum)%></strong>
  </div>

   <hr style="margin:10px 0 10px">

<% end %>

app/views/calculates/new.html.erb
<h1>New calculate</h1>

<%= render 'form' %>

<%= link_to 'Back', calculates_path %>

app/views/calculates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @calculate.name %>
</p>

<p>
  <strong>Money spent:</strong>
  <%= @calculate.money_spent %>
</p>

<%= link_to 'Edit', edit_calculate_path(@calculate) %> |
<%= link_to 'Back', calculates_path %>