config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'

  resources :blogs
  resources :calculates
  resources :users
  match '/signup', to: 'users#new', via: 'get'

  resources :users do
    member do
      get :following, :followers
    end 
  end

  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :microposts, only: [:create, :destroy]
  resources :static_pages
  match '/home', to: 'static_pages#home', via: 'get'
  
  namespace :admin do
    resources :microposts, :users
    get '', to: 'dashboard#index', as: '/'
  end

  

end

app/views/shared/_error_messages.html.erb
<% if @object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
			The form contains <%= pluralize(@object.errors.count, "error") %>.
		</div>
		<ul>
			<% @objectq.errors.full_messages.each do |msg| %>
				<li>* <%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ul class="microposts">
		<%= render partial: 'shared/feed_item', collection: @feed_items %>
	</ul>
	<%= will_paginate @feed_items %>

<% else %>
	<p> There are no micropost.</p>

<% end %>

app/views/shared/_feed_item.html.erb
<li>
	<%= link_to gravatar_for(feed_item.user), feed_item.user %>
	<div class="content">
		<%= feed_item.content %>
		
		<% if feed_item.image.present? %>
			<span><%= image_tag feed_item.image.url(:medium) %></span>
		<% end %> 	
		
	</div>

	<div class="row">
		<div class="pull-right">
		<%= time_ago_in_words(feed_item.created_at) %> ago.

<!-- if current_user is equal to feed_item's user, enable editing and deleting. -->
		<% if current_user?(feed_item.user) %>
			<div class="btn-group">
				<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span class="glyphicon glyphicon-cog"></span> <span class="caret"></span>
				</button>
				<ul class="dropdown-menu" role="menu">
					<li><a href="#">Edit</a></li>
					<li><a href="#"><%= link_to "Delete", feed_item, 
					method: :delete,
					data: { confirm: "Are you sure?" },
					title: feed_item.content %></a></li>
				</ul>
			</div>
		<% end %>

		</div>
	</div>

</li>

app/views/shared/_follow_form.html.erb
<% unless current_user?(@user) %>
	<div id="follow_form">
		<% if current_user.following?(@user) %>
			<%= render 'unfollow' %>
		<% else %>
			<% render 'follow' %>
		<% end %>
	</div>
<% end %>

app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Jung.do</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="/calculates">가계부</a></li>
            <li><a href="/users">유저</a></li>
            <% if is_admin? %>
              <li><a href="/admin">Admin</a></li>
            <% end %>
          </ul>

          <ul class="nav navbar-nav navbar-right">
        
            <% if signed_in? %>
        
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <%= @current_user.name %> <span class="caret"></span>
                  <ul class="dropdown-menu" role="menu">
                    <li><a href="#"><%= link_to "Profile", current_user %></a></li>
                    <li><a href="#"><%= link_to "Settings", edit_user_path(current_user) %></a></li>
                    <li class="divider"></li>
                    <li> <%= link_to "Sign out", signout_path, method: "delete" %></li>
                  </ul>
              </li>

            <% else %>
              <li><%= link_to "Sign in", signin_path %></li>
            <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/shared/_micropost_form.html.erb
<%= form_for @micropost, :html => { multipart: true } do |f| %>
	
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost..." %>
	</div>
	
	<div> Upload image.
		<%= f.file_field :image %>
	</div>

	<div style="margin-top:15px">
		<%= f.submit "Submit", class: "btn btn-large btn-success" %>
	</div>

<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		Following
		<strong id="following" class="stat">
		<%= @user.followed_users.count %>
		</strong>
	</a>
	<a href="<%= followers_user_path(@user) %>">
		Followers
		<strong id="followers" class="stat">
		<%= @user.followers.count %>
		</strong>
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>